<?php
/* @var $this Mage_Adminhtml_Block_Template */
?>
<style type="text/css">
    ul#nav li a.mep {
        background: transparent url(<?php echo $this->getSkinUrl('images/mep-logo-icon.png')?>) no-repeat 15px 4px;
    }
</style>

<script type="text/javascript">
$$('ul#nav li a span').each(function(elem, index){
	if(elem.innerHTML == '<?php echo Mage::helper('mep')->__('MEP');?>'){
	   elem.up('a').addClassName('mep');
       elem.innerHTML = '&ensp;&ensp;&ensp;'+elem.innerHTML;
	}
});
</script>