<div id="container">
    <div id="field_content" class="mapping-dialog">
        <form action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/profile_attribute/edit") ?>" id="mappingform">
            <ul class="formfield_list">
                <li>
                    <label for="attribute_code"><?php echo $this->__('In Database');?></label>
                    <div class="input-box">
                        <select name="attribute_code[]" id="attribute_code" class="chzn-select" multiple="multiple">
                            <?php $aha = Mage::getModel('mep/data')->getExternalAttributes($this->getProfileId()); ?>
                            <?php foreach ($aha as $_value => $_label): ?>
                                <?php if (is_array($_label)): ?>
                                    <optgroup label="<?php echo $_value ?>">
                                        <?php foreach ($_label as $_attributeCode => $_attributeLabel): ?>
                                            <option value="<?php echo $_attributeCode ?>" <?php echo $this->getIsSelectedAttribute($_attributeCode) ? 'selected' : '';?> ><?php echo $_attributeLabel ?></option>
                                        <?php endforeach?>
                                    </optgroup>
                                <?php  else: ?>
                                    <option value="<?php echo $_value ?>" <?php echo $this->getIsSelectedAttribute($_value) ? 'selected' : '';?> ><?php echo $_label ?></option>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="to_field"><?php echo $this->__('To Field');?></label>
                    <div class="input-box">
                        <input type="text" name="to_field" value="<?php echo $this->getMapping()->getToField();?>" id="to_field" class="input-text">
                    </div>
                </li>
                <li>
                    <label for="format"><?php echo $this->__('Format');?></label>
                    <div class="input-box">
                        <input type="text" name="format" value="<?php echo $this->getMapping()->getFormat();?>" id="format" class="input-text">
                    </div>
                </li>
                <li>
                    <label for="position"><?php echo $this->__('Position');?></label>
                    <div class="input-box">
                        <input type="text" name="position" value="<?php echo $this->getMapping()->getPosition();?>" id="position" class="input-text">
                    </div>
                </li>
                <li class="block-checkbox">
                    <label for="inheritance"><?php echo $this->__('Inheritance');?></label>
                    <input type="checkbox" name="inheritance" value="1" <?php if ($this->getMapping()->getInheritance() == 1) echo 'checked="checked"'; ?> id="inheritance" class="input-checkbox">
                </li>
                <li id="inheritance_type_block" <?php if ($this->getMapping()->getInheritance() != 1) echo 'style="display: none;"'; ?>>
                    <div class="input-box">
                        <select name="inheritance_type" id="inheritance_type" class="select">
                            <?php foreach (Mage::getStoreConfig('datas/inheritance_type') as $key => $value) : ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->getMapping()->getInheritanceType() == $key) echo 'selected="selected"'; ?>><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li id="image_url_type_block" <?php if ($this->getMapping()->getAttributeCode() != 'image_url') echo 'style="display: none;"'; ?>>
                    <label for="image_url_type"><?php echo $this->__('Image type');?></label>
                    <div class="input-box">
                        <select name="options[image_url_type]" id="image_url_type" class="select">
                            <option value=""></option>
                            <?php foreach (Mage::getStoreConfig('datas/image_url_type') as $key => $value) : ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->getMapping()->getOption('image_url_type') == $key) echo 'selected="selected"'; ?>><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li id="google_mapping_type_block" <?php if ($this->getMapping()->getAttributeCode() != 'google_mapping') echo 'style="display: none;"'; ?>>
                    <label for="google_mapping_type"><?php echo $this->__('Mapping type');?></label>
                    <div class="input-box">
                        <select name="options[google_mapping_type]" id="google_mapping_type" class="select">
                            <option value=""></option>
                            <?php foreach (Mage::getStoreConfig('datas/google_mapping_type') as $key => $value) : ?>
                                <option value="<?php echo $key; ?>" <?php if ($this->getMapping()->getOption('google_mapping_type') == $key) echo 'selected="selected"'; ?>><?php echo $value; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <label for="google_mapping_separator"><?php echo $this->__('Mapping separator');?></label>
                    <div class="input-box">
                        <input type="text" name="options[google_mapping_separator]" id="google_mapping_separator" class="input-text"/>
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <button type="submit" value="Submit" class="scalable save" title="Submit"><span><span><span><?php echo $this->__('Save');?></span></span></span></button>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="profile_id" value="<?php echo $this->getProfileId() ?>" />
            <input type="hidden" name="id" id="id" value="<?php echo $this->getMapping()->getId();?>" />
        </form>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[
    $('inheritance').observe('change', selectInheritance);

    function    selectInheritance(event) {
        var element = event.element();
        if (element.checked == true) {
            $('inheritance_type_block').show();
        }
        else{
            $('inheritance_type_block').hide();
        }
    }

    AbstractChosen.prototype.set_default_text = function() {
        this.form_field = $('attribute_code');
        this.is_multiple = true;
        if (this.is_multiple) {
            this.default_text = "<?php echo $this->__('Select Some Attributes');?>";
        } else {
            this.default_text =  "<?php echo $this->__('Select a Attribute');?>";
        }
        return this.results_none_found =  "<?php echo $this->__('No results match');?>";
    };

    var chosenObj = new Chosen($$(".chzn-select"));

    Event.observe("mappingform", "submit", function(event) {
        $("mappingform").request({
            onFailure : function() {
            },
            onSuccess : function(t) {
                var parameters = {isAjax: true, profile_id:<?php echo $this->getProfileId() ?>};
                // make another ajax call to reload the fields table
                new Ajax.Request("<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/profile_attribute/index") ?>", {
                    method: "post",
                    parameters: parameters,
                    onSuccess: function(transport)  {
                        if(transport.status == 200) {
                            var response = transport.responseText;
                            $("mapping_grid").update(response);
                        }
                    }
                });
            }
        });
        Event.stop(event);
        mepAttributeSettingsDialog.closeDialog();
        // stop the form from submitting
    });


    /**
     * Add extra field to the form for specific attribute
     */

    var attributesCallback = new Array(
        {attr: 'image_url', callbackSelect: imageUrlOptions, callbackRemove: imageUrlOptionsHide},
        {attr: 'google_mapping', callbackSelect: googleMappingOptions, callbackRemove: googleMappingOptionsHide}
    );

    $$('.active-result').invoke('observe', 'click', function() {
        var position = $(this).id.substr($(this).id.lastIndexOf("_") + 1);
        var item = chosenObj.results_data[position];
        var value = chosenObj.form_field.options[item.options_index].value;
        for (var i = 0; i < attributesCallback.length; i++) {
            if (attributesCallback[i].attr == value) {
                attributesCallback[i].callbackSelect();
            }
        }
    });

    $$('.chzn-choices').invoke('observe', 'click', function(evt) {
        if ($(evt.target).hasClassName('search-choice-close')) {
            var position = $(evt.target).rel;
            var item = chosenObj.results_data[position];
            var value = chosenObj.form_field.options[item.options_index].value;
            for (var i = 0; i < attributesCallback.length; i++) {
                if (attributesCallback[i].attr == value) {
                    attributesCallback[i].callbackRemove();
                }
            }
        }
    });

    function    imageUrlOptions() {
        $('image_url_type_block').show();
    }

    function    imageUrlOptionsHide() {
        $('image_url_type_block').hide();
    }

    function    googleMappingOptions() {
        $('google_mapping_type_block').show();
    }

    function    googleMappingOptionsHide() {
        $('google_mapping_type_block').hide();
    }
    /**
     *
     */

    // ]]>
</script>

