<form action="">
<?php
$aha = $this->getExternalAttributes();

echo $this->__("In Database:") ?> <select name="gui_data[map][db][]" onchange="setMapFileField(this)">
    <?php foreach ($aha as $_value=>$_label): ?>
    <?php if(is_array($_label)):?>
        <optgroup label="<?php echo $_value; ?>">
            <?php foreach($_label as $_attribute):?>
            <option value="<?php echo $_value.':'.$_attribute ?>"><?php echo $_attribute ?></option>
            <?php endforeach;?>
        </optgroup>
        <?php else: ?>
        <option value="<?php echo $_value ?>"><?php echo $_label ?></option>
        <?php endif;?>
    <?php endforeach ?>
</select>
</form>








