<div id="container">
    <div id="field_content" class="mapping-dialog">
        <form action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/shipping_attribute/edit") ?>"
              id="mappingform">
            <ul>
                <li>
                    <label for="payment_method"><?php echo $this->__('Payment Method');?></label>

                    <div class="input-box">
                        <select name="payment_method" id="payment_method">
                            <?php $payments = Mage::getModel('mep/data')->getAllActivePaymentMethods(); ?>
                            <?php foreach ($payments as $_value => $_label): ?>
                                <option value="<?php echo $_value ?>" <?php echo $this->getMapping()->getPaymentMethod() == $_value ? 'selected' : '';?>><?php echo $_label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="shipping_method"><?php echo $this->__('Shipping Method');?></label>

                    <div class="input-box">
                        <select name="shipping_method" id="shipping_method">
                            <?php $shippings = Mage::getModel('mep/data')->getAllShippingMethods(); ?>
                            <?php foreach ($shippings as $_value => $_label): ?>
                                <option value="<?php echo $_value ?>" <?php echo $this->getMapping()->getShippingMethod() == $_value ? 'selected' : '';?>><?php echo $_label ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="country"><?php echo $this->__('Country');?></label>

                    <div class="input-box">
                        <select name="country" id="country">
                            <?php foreach (Mage::getModel('directory/country_api')->items() as $country): ?>
                                <option value="<?php echo $country['country_id'] ?>" <?php echo $this->getMapping()->getCountry() == $country['country_id'] ? 'selected' : '';?>><?php echo $country['name'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </li>
                <li>
                    <label for="position"><?php echo $this->__('Atrribute Code');?></label>

                    <div class="input-box">
                        <input type="text" name="attribute_code"
                               value="<?php echo $this->getMapping()->getAttributeCode();?>" id="position"
                               class="input-text">
                    </div>
                </li>
                <li>
                    <div class="input-box">
                        <?php echo $this->getSaveButtonHtml() ?>
                    </div>
                </li>
            </ul>
            <input type="hidden" name="profile_id" value="<?php echo $this->getProfileId() ?>"/>
            <input type="hidden" name="id" id="id" value="<?php echo $this->getMapping()->getId();?>"/>
        </form>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[

    Event.observe("mappingform", "submit", function (event) {
        $("mappingform").request({
            onFailure:function () {
            },
            onSuccess:function (t) {
                var parameters = {isAjax:true, profile_id:<?php echo $this->getProfileId() ?>};
                // make another ajax call to reload the fields table
                new Ajax.Request("<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/shipping_attribute/index") ?>", {
                    method:"post",
                    parameters:parameters,
                    onSuccess:function (transport) {
                        if (transport.status == 200) {
                            var response = transport.responseText;
                            $("mapping_grid").update(response);
                        }
                    }
                });
            }
        });
        Event.stop(event);
        mepAttributeSettingsDialog.closeDialog();
        // stop the form from submitting
    });
    // ]]>
</script>

