<div id="container" style="display:none">
    <div id="field_content" class="mapping-dialog">
        <form action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/profil_attribute/edit") ?>" id="mappingform">
        <ul>
            <li>
                <label for="attribute_code">Attribute</label>
                <div class="input-box">
                    <select name="attribute_code" id="attribute_code" class="select">
                    <?php $aha = Mage::getModel('mep/data')->getExternalAttributes(); ?>
                    <?php foreach ($aha as $_value => $_label): ?>
                        <?php if (is_array($_label)): ?>
                        <optgroup label="<?php echo $_value ?>">
                        <?php foreach ($_label as $_attribute): ?>
                            <option value="<?php echo $_attribute ?>"><?php echo $_attribute ?></option>
                        <?php endforeach?>
                        </optgroup>
                        <?php  else: ?>
                            <option value="<?php echo $_value ?>"><?php echo $_label ?></option>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </select>
                </div>
            </li>
            <li>
                <label for="to_field">To Field</label>
                <div class="input-box">
                    <input type="text" name="to_field" id="to_field" class="input-text">
                </div>
            </li>
            <li>
                <label for="format">Format</label>
                <div class="input-box">
                    <input type="text" name="format" id="format" class="input-text">
                </div>
            </li>
            <li>
                <label for="position">Position</label>
                <div class="input-box">
                    <input type="text" name="position" id="position" class="input-text">
                </div>
            </li>
            <li>
                <input type="submit" value="Submit" class="form-button">
            </li>
        </ul>
        <input type="hidden" name="profile_id" value="<?php echo $this->getProfile() ?>" />
        <input type="hidden" name="id" id="id" />
        </form>
    </div>
</div>

<script type="text/javascript">
    // <![CDATA[
    var contentWin = null;

    var appliedMapping = function (id) {
        var mappings = $H();
        <?php $mappings = Mage::getModel('mep/mapping')->getCollection()->addFieldToFilter('profile_id', $this->getProfile());?>
        <?php foreach($mappings  as $mapping): ?>
        mappings.set(<?php echo $mapping->getId(); ?>, <?php echo $mapping->toJson(); ?>);
        <?php endforeach; ?>
        return mappings.get(id);
    }

    var doFieldMapping = function(id) {
        if (contentWin != null) {
            Dialog.alert("Close the Mapping Field Window before opening it again!", {
                width : 200,
                height : 130
            });
        } else {
            $("container").show();
            contentWin = new Window({
                className : "attribute-mapping-window",
                maximizable : false,
                resizable : false,
                hideEffect : Element.hide,
                showEffect : Element.show,
                minWidth : 10,
                destroyOnClose : true,
                width : 300,
                height: 190
            });

            //vorbelegung der Werte
            if(id) {
                $H(appliedMapping(id)).each(function(pair){
                    formElement = $(pair.key);
                    if(formElement != null) {
                        $(pair.key).value = pair.value;
                    }
                });
            } else {
                $('mappingform').reset();
                $('id').value = "";
            }

            contentWin.setContent("field_content", false, true)
            contentWin.showCenter(true);
            contentWin.show();

            // Set up a windows observer, check ou debug window to get messages
            myObserver = {
                onDestroy : function(eventName, win) {
                    if (win == contentWin) {
                        $("container").hide();
                        $("container").appendChild($("field_content"));
                        contentWin = null;
                    }
                }
            }
            Windows.addObserver(myObserver);
        }
    }
    window.doFieldMapping = doFieldMapping;
    Event.observe("mappingform", "submit", function(event) {
        contentWin.close();
        $("mappingform").request({
            onFailure : function() {
            },
            onSuccess : function(t) {
                var parameters = {isAjax: true, profile_id:<?php echo $this->getProfile() ?>};
                // make another ajax call to reload the fields table
                new Ajax.Request("<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/profil_attribute/index") ?>", {
                    method: "post",
                    parameters: parameters,
                    onSuccess: function(transport)  {
                        if(transport.status == 200) {
                            var response = transport.responseText;
                            $("rule_tabs_form_fields_content").update(response);
                        }
                    }
                });
            }
        });
        Event.stop(event);
        // stop the form from submitting
    });

    varienGlobalEvents.attachEventHandler('gridRowClick', function(event){
        var id = parseInt(Event.findElement(event, 'tr').down().next().innerHTML);
        doFieldMapping(id);
    });

    // ]]>
</script>
